[tasks.build_release_timing_game]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--example", "timing_game"]

[tasks.build_wasm_timing_game]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./page", "target/wasm32-unknown-unknown/release/examples/timing_game.wasm"]

[tasks.timing_game]
dependencies = [
	"build_release_timing_game",
	"build_wasm_timing_game",
]

[tasks.build_release_click_game]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--example", "click_game"]

[tasks.build_wasm_click_game]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./page", "target/wasm32-unknown-unknown/release/examples/click_game.wasm"]

[tasks.click_game]
dependencies = [
	"build_release_click_game",
	"build_wasm_click_game",
]

[tasks.build_release_2d_shooting]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--example", "2d_shooting"]

[tasks.build_wasm_2d_shooting]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./page", "target/wasm32-unknown-unknown/release/examples/2d_shooting.wasm"]

[tasks.2d_shooting]
dependencies = [
	"build_release_2d_shooting",
	"build_wasm_2d_shooting",
]

[tasks.build_release_frogger]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--example", "frogger"]

[tasks.build_wasm_frogger]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./page", "target/wasm32-unknown-unknown/release/examples/frogger.wasm"]

[tasks.frogger]
dependencies = [
	"build_release_frogger",
	"build_wasm_frogger",
]

[tasks.build_release_flappy_bird]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--example", "flappy_bird"]

[tasks.build_wasm_flappy_bird]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./page", "target/wasm32-unknown-unknown/release/examples/flappy_bird.wasm"]

[tasks.flappy_bird]
dependencies = [
	"build_release_flappy_bird",
	"build_wasm_flappy_bird",
]

[tasks.build_release_catch_game]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--example", "catch_game"]

[tasks.build_wasm_catch_game]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./page", "target/wasm32-unknown-unknown/release/examples/catch_game.wasm"]

[tasks.catch_game]
dependencies = [
	"build_release_catch_game",
	"build_wasm_catch_game",
]
